import { redirect } from "next/navigation";
import Link from "next/link";
import { getCurrentStudent } from "@/lib/dal";
import { getStudentReportCards } from "@/lib/dal/report-cards";
import { ReportCardList } from "@/components/report-cards";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Report Cards | MSU Student Portal",
  description:
    "View and download your official report cards from Mindanao State University.",
};

export const revalidate = 300; // 5 minutes

export default async function ReportCardsPage() {
  const student = await getCurrentStudent();

  if (!student) {
    redirect("/login");
  }

  const reportCards = await getStudentReportCards(student.id);

  return (
    <>
      {/* Breadcrumb */}
      <div className="flex items-center gap-2 text-sm mb-6">
        <Link
          href="/grades"
          className="text-slate-500 dark:text-slate-400 hover:text-primary dark:hover:text-msu-gold"
        >
          Grades
        </Link>
        <span className="material-symbols-outlined text-slate-400 text-[16px]">
          chevron_right
        </span>
        <span className="text-slate-900 dark:text-white font-medium">Report Cards</span>
      </div>

      {/* Page Header */}
      <div className="flex flex-wrap justify-between items-end gap-4 mb-8">
        <div>
          <h1 className="text-slate-900 dark:text-white text-3xl md:text-4xl font-bold leading-tight tracking-tight">
            Report Cards
          </h1>
          <p className="text-slate-500 dark:text-slate-400 text-base mt-2">
            View and download your official academic records.
          </p>
        </div>

        <Link
          href="/grades"
          className="inline-flex items-center gap-2 px-4 py-2.5 bg-slate-100 dark:bg-slate-700 text-slate-700 dark:text-slate-200 rounded-lg font-bold text-sm hover:bg-slate-200 dark:hover:bg-slate-600 transition-colors"
        >
          <span className="material-symbols-outlined text-[18px]">arrow_back</span>
          Back to Grades
        </Link>
      </div>

      {/* Report Cards List */}
      <ReportCardList reportCards={reportCards} />

      {/* Help Note */}
      {reportCards.length > 0 && (
        <div className="mt-8 rounded-xl border border-slate-200 bg-slate-50 dark:bg-slate-800/50 dark:border-slate-700 p-4">
          <div className="flex items-start gap-3">
            <span className="material-symbols-outlined text-slate-400 text-[20px] mt-0.5">
              info
            </span>
            <div>
              <p className="text-sm text-slate-600 dark:text-slate-300">
                Report cards are official documents generated by the Registrar's Office.
                If you notice any discrepancies, please contact the office immediately.
              </p>
              <Link
                href="/help"
                className="inline-flex items-center gap-1 mt-2 text-sm font-bold text-primary dark:text-msu-gold hover:underline"
              >
                Get Help
                <span className="material-symbols-outlined text-[14px]">arrow_forward</span>
              </Link>
            </div>
          </div>
        </div>
      )}
    </>
  );
}
