-- ============================================================
-- Admissions Migration
-- Creates tables required for QR enrollment + application flow
-- Safe to run multiple times (uses IF NOT EXISTS / DO $$ blocks)
-- Run this in the Supabase SQL Editor
-- ============================================================

-- 1. enrollment_qr_codes
-- QR codes generated by admin to allow self-enrollment
CREATE TABLE IF NOT EXISTS enrollment_qr_codes (
  id                   UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  school_id            UUID REFERENCES schools(id) ON DELETE CASCADE,
  created_by           UUID,                           -- admin profile_id
  code                 TEXT NOT NULL UNIQUE,           -- e.g. "MSU-2026-GEN"
  name                 TEXT NOT NULL,
  description          TEXT,
  target_grade_levels  TEXT[]   DEFAULT '{}',
  available_tracks     TEXT[]   DEFAULT '{}',
  max_applications     INTEGER,                        -- NULL = unlimited
  application_count    INTEGER  NOT NULL DEFAULT 0,
  scan_count           INTEGER  NOT NULL DEFAULT 0,
  is_active            BOOLEAN  NOT NULL DEFAULT TRUE,
  enrollment_url       TEXT,
  qr_image_url         TEXT,
  expires_at           TIMESTAMPTZ,
  created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at           TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS enrollment_qr_codes_school_idx ON enrollment_qr_codes(school_id);
CREATE INDEX IF NOT EXISTS enrollment_qr_codes_code_idx   ON enrollment_qr_codes(code);

-- 2. student_applications
-- One row per submitted application (QR or direct)
CREATE TABLE IF NOT EXISTS student_applications (
  id                   UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  school_id            UUID REFERENCES schools(id) ON DELETE SET NULL,
  qr_code_id           UUID REFERENCES enrollment_qr_codes(id) ON DELETE SET NULL,
  student_id           UUID,                           -- set on approval

  -- Applicant info
  first_name           TEXT NOT NULL,
  last_name            TEXT NOT NULL,
  middle_name          TEXT,
  email                TEXT NOT NULL,
  phone                TEXT,
  address              TEXT,
  birth_date           DATE,
  gender               TEXT CHECK (gender IN ('male','female','other')),

  -- Guardian info
  guardian_name        TEXT,
  guardian_phone       TEXT,
  guardian_email       TEXT,
  guardian_relation    TEXT,

  -- Academic info
  previous_school      TEXT,
  last_grade_completed TEXT,
  applying_for_grade   TEXT NOT NULL,
  preferred_track      TEXT,
  gpa                  NUMERIC(4,2),
  how_did_you_hear     TEXT,

  -- Review
  status               TEXT NOT NULL DEFAULT 'submitted'
                         CHECK (status IN ('submitted','under_review','info_requested','approved','rejected','waitlisted')),
  rejection_reason     TEXT,
  requested_documents  TEXT[]  DEFAULT '{}',
  admin_notes          TEXT,
  reviewed_at          TIMESTAMPTZ,
  reviewed_by          UUID,                           -- admin profile_id

  -- Meta
  submitted_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  ip_address           TEXT,
  user_agent           TEXT
);

CREATE INDEX IF NOT EXISTS student_applications_school_idx    ON student_applications(school_id);
CREATE INDEX IF NOT EXISTS student_applications_qr_idx        ON student_applications(qr_code_id);
CREATE INDEX IF NOT EXISTS student_applications_status_idx    ON student_applications(status);
CREATE INDEX IF NOT EXISTS student_applications_submitted_idx ON student_applications(submitted_at DESC);

-- 3. application_documents
-- Files uploaded by the applicant (birth cert, ID photo, etc.)
CREATE TABLE IF NOT EXISTS application_documents (
  id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  application_id   UUID NOT NULL REFERENCES student_applications(id) ON DELETE CASCADE,
  document_type    TEXT NOT NULL,   -- e.g. 'id_photo', 'birth_certificate', 'report_card'
  file_name        TEXT NOT NULL,
  mime_type        TEXT NOT NULL,
  storage_path     TEXT NOT NULL,   -- path inside application-documents bucket
  verified         BOOLEAN NOT NULL DEFAULT FALSE,
  rejection_reason TEXT,
  uploaded_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS application_documents_app_idx ON application_documents(application_id);

-- 4. application_status_log
-- Audit trail of every status change on an application
CREATE TABLE IF NOT EXISTS application_status_log (
  id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  application_id UUID NOT NULL REFERENCES student_applications(id) ON DELETE CASCADE,
  status         TEXT NOT NULL,
  note           TEXT,
  created_by     UUID,            -- admin profile_id (NULL for system actions)
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS application_status_log_app_idx ON application_status_log(application_id);

-- ============================================================
-- Verify tables were created
-- ============================================================
SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'public'
  AND table_name IN (
    'enrollment_qr_codes',
    'student_applications',
    'application_documents',
    'application_status_log'
  )
ORDER BY table_name;
