import { redirect, notFound } from "next/navigation";
import Link from "next/link";
import { getCurrentStudent } from "@/lib/dal";
import { getReportCard } from "@/lib/dal/report-cards";
import { ReportCardView } from "@/components/report-cards";
import { ReportCardDownload } from "@/components/report-cards/ReportCardDownload";
import type { Metadata } from "next";

interface ReportCardDetailPageProps {
  params: Promise<{ id: string }>;
}

export async function generateMetadata({
  params,
}: ReportCardDetailPageProps): Promise<Metadata> {
  const { id } = await params;
  const student = await getCurrentStudent();

  if (!student) {
    return { title: "Report Card | MSU Student Portal" };
  }

  const reportCard = await getReportCard(id, student.id);

  if (!reportCard) {
    return { title: "Report Card Not Found | MSU Student Portal" };
  }

  return {
    title: `${reportCard.grading_period?.name || "Report Card"} | MSU Student Portal`,
    description: `View your report card for ${reportCard.grading_period?.name || "the grading period"} at Mindanao State University.`,
  };
}

export const revalidate = 300; // 5 minutes

export default async function ReportCardDetailPage({
  params,
}: ReportCardDetailPageProps) {
  const { id } = await params;
  const student = await getCurrentStudent();

  if (!student) {
    redirect("/login");
  }

  const reportCard = await getReportCard(id, student.id);

  if (!reportCard) {
    notFound();
  }

  return (
    <>
      {/* Breadcrumb */}
      <div className="flex items-center gap-2 text-sm mb-6">
        <Link
          href="/grades"
          className="text-slate-500 dark:text-slate-400 hover:text-primary dark:hover:text-msu-gold"
        >
          Grades
        </Link>
        <span className="material-symbols-outlined text-slate-400 text-[16px]">
          chevron_right
        </span>
        <Link
          href="/grades/report-cards"
          className="text-slate-500 dark:text-slate-400 hover:text-primary dark:hover:text-msu-gold"
        >
          Report Cards
        </Link>
        <span className="material-symbols-outlined text-slate-400 text-[16px]">
          chevron_right
        </span>
        <span className="text-slate-900 dark:text-white font-medium truncate max-w-[150px]">
          {reportCard.grading_period?.name || "Report Card"}
        </span>
      </div>

      {/* Page Header */}
      <div className="flex flex-wrap justify-between items-start gap-4 mb-8">
        <div>
          <h1 className="text-slate-900 dark:text-white text-3xl md:text-4xl font-bold leading-tight tracking-tight">
            {reportCard.grading_period?.name || "Report Card"}
          </h1>
          <p className="text-slate-500 dark:text-slate-400 text-base mt-2">
            Academic Year: {reportCard.grading_period?.academic_year || "N/A"}
            {reportCard.released_at && (
              <span className="ml-3 text-sm">
                Released on {new Date(reportCard.released_at).toLocaleDateString("en-US", {
                  year: "numeric",
                  month: "long",
                  day: "numeric",
                })}
              </span>
            )}
          </p>
        </div>

        <div className="flex items-center gap-3">
          <ReportCardDownload reportCard={reportCard} />
          <Link
            href="/grades/report-cards"
            className="inline-flex items-center gap-2 px-4 py-2.5 bg-slate-100 dark:bg-slate-700 text-slate-700 dark:text-slate-200 rounded-lg font-bold text-sm hover:bg-slate-200 dark:hover:bg-slate-600 transition-colors"
          >
            <span className="material-symbols-outlined text-[18px]">arrow_back</span>
            <span className="hidden sm:inline">Back</span>
          </Link>
        </div>
      </div>

      {/* Report Card View */}
      <ReportCardView reportCard={reportCard} />

      {/* Help Note */}
      <div className="mt-8 rounded-xl border border-slate-200 bg-slate-50 dark:bg-slate-800/50 dark:border-slate-700 p-4">
        <div className="flex items-start gap-3">
          <span className="material-symbols-outlined text-slate-400 text-[20px] mt-0.5">
            info
          </span>
          <div>
            <p className="text-sm text-slate-600 dark:text-slate-300">
              This is an official document generated by the Registrar's Office.
              If you notice any discrepancies in your grades or information, please contact
              the office immediately.
            </p>
            <div className="flex flex-wrap gap-4 mt-3">
              <Link
                href="/help"
                className="inline-flex items-center gap-1 text-sm font-bold text-primary dark:text-msu-gold hover:underline"
              >
                Get Help
                <span className="material-symbols-outlined text-[14px]">arrow_forward</span>
              </Link>
              <Link
                href="/messages"
                className="inline-flex items-center gap-1 text-sm font-bold text-slate-600 dark:text-slate-300 hover:underline"
              >
                Contact Registrar
                <span className="material-symbols-outlined text-[14px]">mail</span>
              </Link>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
